package selenium.basic;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class ManyFacultyTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void manyFacultyTeset() {
        driver.get("http://localhost:8080/docthesistracker_war_exploded/views/anonymous/login.xhtml");
        driver.manage().window().setSize(new Dimension(1269, 813));
        driver.findElement(By.id("login-form:email-itxt")).click();
        driver.findElement(By.id("login-form:email-itxt")).sendKeys("jane@example.com");
        driver.findElement(By.id("login-form:password-iscrt")).click();
        driver.findElement(By.id("login-form:password-iscrt")).sendKeys("Password@123");
        driver.findElement(By.id("login-form:login-cbtn")).click();
        driver.findElement(By.id("navbarForm:selected-faculty-slom")).click();
        {
            WebElement dropdown = driver.findElement(By.id("navbarForm:selected-faculty-slom"));
            dropdown.findElement(By.xpath("//option[. = 'Faculty of Engineering']")).click();
        }
        driver.findElement(By.id("j_idt47:aktiv-all-cir-btn")).click();
        driver.findElement(By.id("navbarForm:selected-faculty-slom")).click();
        {
            WebElement dropdown = driver.findElement(By.id("navbarForm:selected-faculty-slom"));
            dropdown.findElement(By.xpath("//option[. = 'Faculty of Science']")).click();
        }
        driver.findElement(By.id("j_idt47:aktiv-all-cir-btn")).click();
        driver.findElement(By.id("navbarForm:selected-faculty-slom")).click();
        {
            WebElement dropdown = driver.findElement(By.id("navbarForm:selected-faculty-slom"));
            dropdown.findElement(By.xpath("//option[. = 'Faculty of Arts']")).click();
        }
        {
            WebElement element = driver.findElement(By.id("j_idt47:aktiv-all-cir-btn"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.id("j_idt47:aktiv-all-cir-btn")).click();
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("navbarForm:logout-cbtn")).click();
    }
}
